name: create

on:
  workflow_call:
    inputs:
      RESOURCE_GROUP_NAME:
        type: string
      LOCATION:
        type: string
      VM_IMAGE:
        type: string
      VM_SPOT:
        type: string
      VM_SIZE:
        type: string
      VM_DISK_SIZE:
        type: string
      VM_NAME:
        type: string
      VM_USERNAME:
        type: string
      STORAGE_BLOB_URI:
        type: string
      SSH_KEY_BASENAME:
        type: string
        required: false
        default: "id_rsa"
      RUNNER_LABEL:
        type: string
        required: true
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      GH_TOKEN:
        description: Token with admin repo privilege
        required: false
      GH_APP_ID:
        description: App id with admin privilege
        required: false
      GH_PRIVATE_KEY:
        description: App private key with admin privilege
        required: false
    outputs:
      uniq_label:
        value: ${{ jobs.create.outputs.uniq_label }}

# permissions:
#   id-token: write
#   contents: read

jobs:
  create:
    runs-on: ubuntu-latest
    outputs:
      uniq_label: ${{ steps.uniqlabel.outputs.label }}
    steps:
      - name: Test secrets 1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
        if: ${{ env.GH_TOKEN == '' && (env.GH_APP_ID == '' || env.GH_PRIVATE_KEY == '') }}
        run: echo Error [GH_TOKEN] or [GH_APP_ID, GH_PRIVATE_KEY] are not defined  >> /dev/stderr; false

      - name: Test secrets 2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
        if: ${{ env.GH_TOKEN != '' && ( env.GH_APP_ID != '' || env.GH_PRIVATE_KEY != '' ) }}
        run: echo Error [GH_TOKEN] and [GH_APP_ID, GH_PRIVATE_KEY] are defined  >> /dev/stderr; false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Jason-Clark-FG/azure-github-runner
          ref: main

      - name: Generate ssh key
        run: ssh-keygen -b 2048 -f ~/.ssh/${{ inputs.SSH_KEY_BASENAME }} -N ""

      - name: Config ssh
        run: touch ~/.ssh/known_hosts

      - name: Generate a unique label
        id: uniqlabel
        run: 'echo label=${{ inputs.RUNNER_LABEL }} >> "$GITHUB_OUTPUT"'

      - name: Upload ssh key
        uses: actions/upload-artifact@v4
        with:
          name: ssh-${{ inputs.SSH_KEY_BASENAME }}
          path: ~/.ssh/${{ inputs.SSH_KEY_BASENAME }}*
          retention-days: 1
          overwrite: true
          include-hidden-files: true

      - name: login to azure
        uses: Azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      - name: Run script with gh token
        if: ${{ env.GH_TOKEN != '' }}
        env:
          GITHUB_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          RUN_ID: ${{ github.run_id }}
          RESOURCE_GROUP_NAME: ${{ inputs.RESOURCE_GROUP_NAME }}
          LOCATION: ${{ inputs.LOCATION }}
          VM_IMAGE: ${{ inputs.VM_IMAGE }}
          VM_SPOT: ${{ inputs.VM_SPOT }}
          VM_SIZE: ${{ inputs.VM_SIZE }}
          VM_DISK_SIZE: ${{ inputs.VM_DISK_SIZE }}
          VM_NAME: ${{ inputs.VM_NAME }}
          VM_USERNAME: ${{ inputs.VM_USERNAME }}
          STORAGE_BLOB_URI: ${{ inputs.STORAGE_BLOB_URI }}
          UNIQ_LABEL: ${{ steps.uniqlabel.outputs.label }}
          SSH_KEY_BASENAME: ${{ inputs.SSH_KEY_BASENAME }}
        run: ./main.sh | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> "$GITHUB_OUTPUT"

      - uses: actions/create-github-app-token@v1
        id: app-token
        if: ${{ failure() && env.GH_TOKEN == '' }}
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: Run script with appid & pkey
        if: ${{ steps.app-token.outcome == 'success' }}
        env:
          GITHUB_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          RUN_ID: ${{ github.run_id }}
          RESOURCE_GROUP_NAME: ${{ inputs.RESOURCE_GROUP_NAME }}
          LOCATION: ${{ inputs.LOCATION }}
          VM_IMAGE: ${{ inputs.VM_IMAGE }}
          VM_SPOT: ${{ inputs.VM_SPOT }}
          VM_SIZE: ${{ inputs.VM_SIZE }}
          VM_DISK_SIZE: ${{ inputs.VM_DISK_SIZE }}
          VM_NAME: ${{ inputs.VM_NAME }}
          VM_USERNAME: ${{ inputs.VM_USERNAME }}
          STORAGE_BLOB_URI: ${{ inputs.STORAGE_BLOB_URI }}
          UNIQ_LABEL: ${{ steps.uniqlabel.outputs.label }}
          SSH_KEY_BASENAME: ${{ inputs.SSH_KEY_BASENAME }}
        run: ./main.sh | jq -r 'keys[] as $k | "\($k)=\(.[$k])"' >> "$GITHUB_OUTPUT"
