name: delete

on:
  workflow_call:
    secrets:
      ARM_CLIENT_ID:
        required: true
      ARM_CLIENT_SECRET:
        required: true
      ARM_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
      GH_TOKEN:
        description: Token with admin repo privilege
        required: false
      GH_APP_ID:
        description: App id with admin privilege
        required: false
      GH_PRIVATE_KEY:
        description: App private key with admin privilege
        required: false

# permissions:
#   id-token: write
#   contents: read

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - name: Test secrets 1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
        if: ${{ env.GH_TOKEN == '' && (env.GH_APP_ID == '' || env.GH_PRIVATE_KEY == '') }}
        run: echo Error [GH_TOKEN] or [GH_APP_ID, GH_PRIVATE_KEY] are not defined  >> /dev/stderr; false

      - name: Test secrets 2
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_APP_ID: ${{ secrets.GH_APP_ID }}
          GH_PRIVATE_KEY: ${{ secrets.GH_PRIVATE_KEY }}
        if: ${{ env.GH_TOKEN != '' && ( env.GH_APP_ID != '' || env.GH_PRIVATE_KEY != '' ) }}
        run: echo Error [GH_TOKEN] and [GH_APP_ID, GH_PRIVATE_KEY] are defined  >> /dev/stderr; false

      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: Jason-Clark-FG/azure-github-runner
          ref: main

      - name: Download ssh key
        uses: actions/download-artifact@v4
        with:
          name: ssh
          path: ~/.ssh

      - name: Set ssh key permission
        run: chmod 400 ~/.ssh/id_rsa

      - name: login to azure
        uses: Azure/login@v2
        with:
          creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

      - name: Run script with gh token
        if: ${{ env.GH_TOKEN != '' }}
        env:
          GITHUB_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          RUN_ID: ${{ github.run_id }}
        run: ./main.sh --destroy

      - uses: actions/create-github-app-token@v1
        id: app-token
        if: ${{ failure() && env.GH_TOKEN == '' }}
        with:
          app-id: ${{ secrets.GH_APP_ID }}
          private-key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: Run script with appid & pkey
        if: ${{ steps.app-token.outcome == 'success' }}
        env:
          GITHUB_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          RUN_ID: ${{ github.run_id }}
        run: ./main.sh --destroy

