name: test create runner

on:
  workflow_dispatch:

jobs:
  create:
    uses: Jason-Clark-FG/azure-github-runner/.github/workflows/create.yml@main
    with:
      VM_SIZE: Standard_B2s
      LOCATION: westus2
      STORAGE_ACCOUNT_NAME: sfgdwus2jcinstallmedia
      STORAGE_RESOURCE_GROUP_NAME: rg-d-wus2-jclark
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  test:
    runs-on: ${{ needs.create.outputs.uniq_label }}
    needs: create
    steps:
      - run: echo running on azure:${{ needs.create.outputs.uniq_label }}
    
  delete:
    needs: test
    uses: Jason-Clark-FG/azure-github-runner/.github/workflows/delete.yml@main
    if: ${{ always() }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
