name: test create runner

on:
  workflow_dispatch:

jobs:
  create:
    uses: Jason-Clark-FG/azure-github-runner/.github/workflows/create.yml@main
    with:
      RESOURCE_GROUP_NAME: "rg-t-ghrunner-01"
      LOCATION: "westus2"
      VM_IMAGE: "canonical:ubuntu-24_04-lts:server:latest"
      VM_SIZE: "Standard_B2s"
      VM_DISK_SIZE: "127"
      VM_NAME: "az-ghr-01d"
      VM_USERNAME: "ghradmin"
      STORAGE_BLOB_URI: ""
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

  test:
    runs-on: ${{ needs.create.outputs.uniq_label }}
    needs: create
    steps:
      - run: echo running on azure:${{ needs.create.outputs.uniq_label }}

  delete:
    needs: test
    uses: Jason-Clark-FG/azure-github-runner/.github/workflows/delete.yml@main
    if: ${{ always() }}
    with:
      RESOURCE_GROUP_NAME: "rg-t-ghrunner-01"
      VM_NAME: "az-ghr-01d"
      VM_USERNAME: "ghradmin"
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
