name: test create runner

on:
  workflow_dispatch:

jobs:
  create:
    uses: logiroad/azure-github-runner/.github/workflows/create.yml@main
    with:
      VM_SIZE: Standard_B1s
      LOCATION: northeurope
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs: create
    steps:
      - run: echo ${{ needs.create.outputs.uniq_label }}
    
  delete:
    needs: test
    uses: logiroad/azure-github-runner/.github/workflows/delete.yml@main
    if: ${{ always() }}
    secrets:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

